sudo: false
dist: trusty

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.2.9

script:
  - bundle exec rspec --format progress
