sudo: false
dist: trusty

language: ruby

rvm:
  - 2.2.7
  - 2.3.5
  - 2.4.2
  - 2.5.0

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.5.0

script:
  - bundle exec rspec --format progress
